<div class="ajax-login">
    <ul class="form-list">
        <li>
            <h2><?php echo $this->__('Please login to be notified when this product is back in stock.') ?></h2>
        </li>
        <li class="error">
            <p></p>
        </li>
        <li>
            <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
                <input type="text" name="username" value="" id="email" class="input-text" title="Email Address" />
            </div>
        </li>
        <li>
            <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
            <div class="input-box">
                <input type="password" name="password" class="input-text" id="pass" title="Password" />
            </div>
        </li>
        <li class="f-right">
            <button type="submit" class="button" title="Login" name="send" id="login-btn">
                <span>
                    <span><?php echo $this->__('Login') ?></span>
                </span>
            </button>
        <li>
    </ul>
    <a href="javascript:void(0);" class="close">X</a>
</div>